Change deployment strategy

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,8 +12,129 @@ env:
   GIT_NAME: "guzel.khuziakhmetova"
 
 jobs:
+  build_and_push_image:
+    name: Build and push image
+    runs-on: ubuntu-latest
+    steps:
+      -   name: Checkout Code from repository
+          uses: actions/checkout@v2
+      -   name: Login to Docker Hub
+          uses: docker/login-action@v1
+          with:
+            username: ${{ secrets.DOCKERHUB_USERNAME }}
+            password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+      -   name: Build and push Docker image
+          uses: docker/build-push-action@v2
+          with:
+            context: ./app/
+            push: true
+            tags: guzelkhuziakhmetova/go-api-task:${{ env.RUN_NUMBER }}
+
+  modify_image_tag:
+    name: Modify image tag
+    needs: build_and_push_image
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+        name: Changing the deployment of git repo
+        with:
+          repository: GuzelSwon/go-api-task2-k8s-deployment
+          token: ${{ env.AUTH_GITHUB_TOKEN }}
+          ref: main
+      - name: modify the image
+        run: |
+          git config user.email $GIT_EMAIL
+          git config user.name $GIT_NAME
+          echo "Working Directory: $(pwd)"
+  
+          # Navigate to the specific Helm chart directory
+          cd helm-chart
+  
+          # Print values.yaml for debugging before changes
+          echo "Before modification:"
+          cat values.yaml
+  
+          sed -i '/^image:/,/^  tag:/{s/^  tag: .*/  tag: "'$RUN_NUMBER'"/}' values.yaml
+  
+          # Print values.yaml for debugging after changes
+          echo "After modification:"
+          cat values.yaml
+  
+          git add values.yaml
+          git commit -m "Update image tag by Github Actions Job change manifest: '$RUN_NUMBER'"
+          git push origin main
+
+  test_application:
+    name: Run tests
+    runs-on: ubuntu-latest
+    needs: modify_image_tag
+    steps:
+      - uses: actions/setup-go@v5
+        name: Setup Go
+        with:
+          go-version: '1.22.2'
+      - name: Install dependencies
+        uses: actions/checkout@v3
+      - run: | 
+          cd app/
+          go mod download
+      - name: Test with Go
+        uses: actions/checkout@v3
+      - run: |
+          cd app/tests
+          go test -json > TestResults-$RUN_NUMBER.json
+      - name: Upload Go test results
+        uses: actions/upload-artifact@v4
+        with:
+          name: Go-results-${{ env.RUN_NUMBER }}
+          path: TestResults-${{ env.RUN_NUMBER }}.json
+      - name: Verify tests
+        run: | 
+          if grep FAIL TestResults-$RUN_NUMBER.json; then exit 1
+          fi
+
+  perform_rollback:
+    name: Perform rollback
+    runs-on: ubuntu-latest
+    needs: test_application
+    if: failure()
+    steps:
+      - uses: actions/checkout@v3
+        name: Rollback main branch
+        with:
+          repository: GuzelSwon/go-api-task2-k8s-deployment
+          token: ${{ env.AUTH_GITHUB_TOKEN }}
+          ref: main
+      - run: |
+          echo "Perform Rollback because Tests Failed"
+          git config user.email $GIT_EMAIL
+          git config user.name $GIT_NAME
+          echo "Working Directory: $(pwd)"
+          
+          # Navigate to the specific Helm chart directory
+          cd helm-chart
+          
+          # Print values.yaml for debugging before changes
+          echo "Before modification:"
+          cat values.yaml
+          
+          sed -i '/^image:/,/^  tag:/{s/^  tag: .*/  tag: "$PREVIOUS_RUN_NUMBER"/}' values.yaml
+          
+          # Print values.yaml for debugging after changes
+          echo "After modification:"
+          cat values.yaml
+          
+          git add values.yaml
+          git commit -m "Rolled back image tag by Github Actions Job change manifest: $PREVIOUS_RUN_NUMBER"
+          git push origin main
+
+        env:
+          PREVIOUS_RUN_NUMBER: ${{ vars.PREVIOUS_RUN_NUMBER }}
+
   deploy:
     name: Deploy app
+    needs: test_application
     environment: production
     runs-on: ubuntu-latest
     if: success()
